- name: Preflight
  tags: always
  include_tasks: 
    file: "{{ _os }}/00-preflight.yml"

- name: Install and configure Consul
  tags: config
  include_tasks: 
    file: "{{ _os }}/01-install.yml"

- name: Add services
  tags: services
  include_tasks: 
    file: "{{ _os }}/02-services.yml"

- name: Add configs
  tags: config
  include_tasks: 
    file: "{{ _os }}/03-configs.yml"

- name: Add scripts
  tags: scripts
  include_tasks: 
    file: "{{ _os }}/04-scripts.yml"
