- name: download consul to localhost
  become: false
  run_once: true
  delegate_to: localhost
  get_url:
    url: "{{ _archive_url }}"
    dest: "{{ role_path }}/files/{{ _archive }}"
    checksum: "sha256:{{ _archive_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2

- name: create consul directories
  win_file:
    path: "{{ dir.value.path }}"
    state: directory
  loop: "{{ consul_dirs | dict2items }}"
  loop_control:
    loop_var: dir
    label: "{{ dir.key }}"

- name: create archive directory
  become: false
  delegate_to: localhost
  file:
    state: directory
    path: "{{ _archive_dir }}"

- name: unpack consul
  become: false
  delegate_to: localhost
  unarchive:
    src: "{{ role_path }}/files/{{ _archive }}"
    dest: "{{ _archive_dir }}"
    creates: "{{ _archive_dir }}/consul"

- name: propagate consul binary
  win_copy:
    src: "{{ _archive_dir }}/consul.exe"
    dest: "{{ consul_dir }}/consul.exe"
  notify: restart consul service

- name: delete archive directory
  become: false
  delegate_to: localhost
  file:
    dest: "{{ _archive_dir }}"
    state: absent
  when: not lookup("env", "MOLECULE_SCENARIO_NAME") | default("")

- name: create consul config
  tags: config
  win_copy:
    content: "{{ consul_config | to_nice_json }}"
    dest: "{{ consul_dirs.main.path }}/consul.json"
    validate: "consul validate -config-format=json %s"
  notify: restart consul service

- name: enable consul
  win_service: 
    name: consul
    path: "{{ consul_dirs.main.path }}\\consul.exe agent -config-file={{ consul_dirs.main.path }}/consul.json -config-dir={{ consul_dirs.configs.path }}"
    description: "consul.io"
    state: stopped

